---
- hosts: localhost
  connection: local

  tasks:

  - name: create reveal link
    command: ln -s revelator/reveal_js_261 ./reveal_js_261 creates=./reveal_js_261

  - name: create dest dir
    command: mkdir -p output
 
  - name: syntax check fundamentals
    shell: python syntax_check.py fundamentals/*.yml

  - name: syntax check operational 
    shell: python syntax_check.py operational/*.yml

  - name: syntax check advanced 
    shell: python syntax_check.py advanced/*.yml

  - name: syntax check scilifelab 
    shell: python syntax_check.py scilifelab/*.yml

  - name: build fundamentals
    shell: python build_single.py fundamentals > output/fundamentals.yml
 
  - name: build operational
    shell: python build_single.py operational > output/operational.yml

  - name: build advanced 
    shell: python build_single.py advanced > output/advanced.yml

  - name: build scilifelab 
    shell: python build_single.py scilifelab > output/scilifelab.yml

  - name: render fundamentals
    command: revelator/write_it output/fundamentals.yml output/fundamentals/

  - name: render operational 
    command: revelator/write_it output/operational.yml output/operational/

  - name: render advanced 
    command: revelator/write_it output/advanced.yml output/advanced/
  
  - name: render scilifelab
    command: revelator/write_it output/scilifelab.yml output/scilifelab/
